-------------------
fatal error: libv4l2.h: No such file or directory
   54 | #include <libv4l2.h>

sudo apt-get install libv4l-dev

-------------------

/home/dt/HRIPapers/hand_eye_ws/src/aslam_cv2/aslam_cv_common/include/aslam/common/internal/unique-id.h:7:10: fatal error: aslam/common/id.pb.h: No such file or directory
    7 | #include "aslam/common/id.pb.h"

https://github.com/ethz-asl/aslam_cv2/issues/52#issuecomment-706067723

-------------------

segfault due to reading from uninitialised error

https://github.com/ardiya/hand_eye_calibration/commit/41ae4a94b0df587e1b530da0e572a857d0290b35

-------------------

  File "/home/dt/HRIPapers/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/python/hand_eye_calibration/time_alignment.py", line 146, in calculate_time_offset
    (quaternions_A_interp, samples_A) = resample_quaternions(times_A,
  File "/home/dt/HRIPapers/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/python/hand_eye_calibration/time_alignment.py", line 98, in resample_quaternions
    samples = np.linspace(times[0], times[-1], interval / dt + 1)
  File "<__array_function__ internals>", line 200, in linspace
  File "/home/dt/.local/lib/python3.8/site-packages/numpy/core/function_base.py", line 121, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer


on line 98 in time_alignment.py
samples = np.linspace(times[0], times[-1], int(interval / dt) + 1)

-------------------


/home/dt/HRIPapers/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/python/hand_eye_calibration/dual_quaternion.py:39: FutureWarning: In the future `np.str` will be defined as the corresponding NumPy scalar.
  return "[q_rot: {}, q_dual: {}]".format(np.str(self.q_rot), np.str(self.q_dual))
Traceback (most recent call last):
  File "/home/dt/HRIPapers/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/bin/compute_hand_eye_calibration.py", line 142, in <module>
    runtime, singular_values, bad_singular_values) = compute_hand_eye_calibration_RANSAC(
  File "/home/dt/HRIPapers/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/python/hand_eye_calibration/dual_quaternion_hand_eye_calibration.py", line 879, in compute_hand_eye_calibration_RANSAC
    print("Found a new best sample: {}\n"
  File "/home/dt/HRIPapers/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/python/hand_eye_calibration/dual_quaternion.py", line 39, in __str__
    return "[q_rot: {}, q_dual: {}]".format(np.str(self.q_rot), np.str(self.q_dual))
  File "/home/dt/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'str'.
`np.str` was a deprecated alias for the builtin `str`. To avoid this error in existing code, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations


in line 39 of dual_quaternion.py replaced np.str with str

------------------


/home/dt/HRIPapers/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/python/hand_eye_calibration/quaternion.py:29: FutureWarning: In the future `np.str` will be defined as the corresponding NumPy scalar.
  return np.str(self.q)
Traceback (most recent call last):
  File "/home/dt/HRIPapers/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/bin/compute_hand_eye_calibration.py", line 142, in <module>
    runtime, singular_values, bad_singular_values) = compute_hand_eye_calibration_RANSAC(
  File "/home/dt/HRIPapers/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/python/hand_eye_calibration/dual_quaternion_hand_eye_calibration.py", line 879, in compute_hand_eye_calibration_RANSAC
    print("Found a new best sample: {}\n"
  File "/home/dt/HRIPapers/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/python/hand_eye_calibration/dual_quaternion.py", line 39, in __str__
    return "[q_rot: {}, q_dual: {}]".format(str(self.q_rot), str(self.q_dual))
  File "/home/dt/HRIPapers/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/python/hand_eye_calibration/quaternion.py", line 29, in __str__
    return np.str(self.q)
  File "/home/dt/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'str'.
`np.str` was a deprecated alias for the builtin `str`. To avoid this error in existing code, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

in line 29 of quaternion.py replaced np.str with str

------------------
