-------------------
fatal error: libv4l2.h: No such file or directory
   54 | #include <libv4l2.h>

sudo apt-get install libv4l-dev

-------------------

/home/dt/HRIPapers/hand_eye_ws/src/aslam_cv2/aslam_cv_common/include/aslam/common/internal/unique-id.h:7:10: fatal error: aslam/common/id.pb.h: No such file or directory
    7 | #include "aslam/common/id.pb.h"

https://github.com/ethz-asl/aslam_cv2/issues/52#issuecomment-706067723

-------------------

segfault due to reading from uninitialised error

https://github.com/ardiya/hand_eye_calibration/commit/41ae4a94b0df587e1b530da0e572a857d0290b35

-------------------

  File "/home/dt/HRIPapers/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/python/hand_eye_calibration/time_alignment.py", line 146, in calculate_time_offset
    (quaternions_A_interp, samples_A) = resample_quaternions(times_A,
  File "/home/dt/HRIPapers/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/python/hand_eye_calibration/time_alignment.py", line 98, in resample_quaternions
    samples = np.linspace(times[0], times[-1], interval / dt + 1)
  File "<__array_function__ internals>", line 200, in linspace
  File "/home/dt/.local/lib/python3.8/site-packages/numpy/core/function_base.py", line 121, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer


on line 98 in time_alignment.py
samples = np.linspace(times[0], times[-1], int(interval / dt) + 1)

-------------------
